version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: cimg/ruby:3.0.0-node
        environment:
          RAILS_ENV: test
          PGHOST: 127.0.0.1
          PGUSER: root

      - image: circleci/postgres:latest
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: goal-tracker-test
          POSTGRES_PASSWORD: $POSTGRES_PASSWORD

    executor: ruby/default
    steps:
      - checkout

      # Restore cached dependencies
      # - type: cache-restore
      #   name: Restore bundle cache
      #   key: goal-tracker-{{ checksum "Gemfile.lock" }}

      # Install bundle dependencies
      - run: bundle config set --local path 'vendor/bundle'
      - run: bundle install

      # # Cache dependencies
      # - type: cache-save
      #   name: Store bundle cache
      #   key: goal-tracker-{{ checksum "Gemfile.lock" }}
      #   path: vendor/bundle
        
      - run: bundle exec rake db:setup


  test:
    docker:
      - image: cimg/ruby:3.0.0-node
        environment:
          RAILS_ENV: test
          PGHOST: 127.0.0.1
          PGUSER: root

      - image: circleci/postgres:latest
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: goal-tracker-test
          POSTGRES_PASSWORD: $POSTGRES_PASSWORD

    executor: ruby/default
    steps:
      - run: mkdir ~/rspec
      - run:
          command: bundle exec rspec --format progress --format RspecJunitFormatter -o ~/rspec/rspec.xml
          when: always
      - store_test_results:
          path: ~/rspec


workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build