version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 


jobs:
  build:
    docker:
      - image: cimg/ruby:3.0.0-node
        environment:
          RAILS_ENV: test
          PGHOST: 127.0.0.1
          PGUSER: root

    executor: ruby/default
    steps:
      - checkout

      # Restore dependency caches
      - restore_cache:
          name: Restore bundle cache
          keys: 
            - goals-tracker-bundle-{{ checksum "Gemfile.lock" }}
      - restore_cache:
          name: Restore yarn cache
          keys:
            - goals-tracker-yarn-{{ checksum "yarn.lock" }}

      # Install bundle dependencies
      - run: 
          name: Bundle Install in `vendor/bundle`
          command: |
            bundle config set --local path 'vendor/bundle'
            bundle install

      # Install yarn dependencies
      - run: 
          name: Yarn Install
          command: yarn install --cache-folder vendor/yarn

      # Cache dependencies
      - save_cache:
          name: Store bundle cache
          key: goals-tracker-bundle-{{ checksum "Gemfile.lock" }}
          paths: 
            - vendor/bundle
      - save_cache:
          name: Store yarn cache
          key: goals-tracker-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      # Persist built dependencies to workspace
      - persist_to_workspace:
          root: vendor
          paths: 
            - bundle
            - yarn



  test:
    docker:
      - image: cimg/ruby:3.0.0-node
        environment:
          RAILS_ENV: test
          PGHOST: 127.0.0.1
          PGUSER: root
          CC_TEST_REPORTER_ID: 1fbaaed8f79723cf36f267c7aa335cf81cf61b45c635456649d895a46a417028

      - image: circleci/postgres:latest
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: goals-tracker-test
          POSTGRES_PASSWORD: $POSTGRES_PASSWORD

    executor: ruby/default
    steps:
      - checkout

      # Use built dependencies from build job
      - attach_workspace:
          at: vendor
      - run: 
          name: Configure bundler to use `vendor/bundle`
          command: bundle config set --local path 'vendor/bundle'
      - run: 
          name: Run `yarn install` with `vendor/yarn` as cache folder
          command: yarn install --cache-folder vendor/yarn

      # Install Code Climate Test Reporter
      - run:
          name: Install Code Climate Test Reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter

      # Set up database
      - run: 
          name: Set up database
          command: bundle exec rake db:setup

      # Run tests & coverage
      - run:
          name: Run tests
          command: |
            mkdir -p ~/rspec test-artifacts
            ./cc-test-reporter before-build
            bundle exec rspec --format progress --format RspecJunitFormatter -o ~/rspec/rspec.xml
      - run:
          name: Code Climate Test Coverage
          command: |
            ./cc-test-reporter format-coverage -t simplecov -o "coverage/codeclimate.$CIRCLE_NODE_INDEX.json"

      # Extract test results
      - persist_to_workspace:
          root: coverage
          paths:
            - codeclimate.*.json
      - store_test_results:
          path: ~/rspec
      - store_artifacts:
          path: test-artifacts



  upload-coverage:
    docker:
      - image: cimg/ruby:3.0.0-node
        environment:
          CC_TEST_REPORTER_ID: 1fbaaed8f79723cf36f267c7aa335cf81cf61b45c635456649d895a46a417028
    
    executor: ruby/default
    steps:
      # Use extracted code coverage
      - attach_workspace:
          at: coverage

      # Install Code Climate Test Reporter
      - run:
          name: Install Code Climate Test Reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter

      # Upload coverage results
      - run:
          name: Upload coverage results
          command: |
            ./cc-test-reporter sum-coverage --output - coverage/codeclimate.*.json | ./cc-test-reporter upload-coverage --debug --input -




workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - upload-coverage:
          requires:
            - test
