version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: cimg/ruby:3.0.0-node
        environment:
          RAILS_ENV: test
          PGHOST: 127.0.0.1
          PGUSER: root

      - image: circleci/postgres:latest
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: goal-tracker-test
          POSTGRES_PASSWORD: $POSTGRES_PASSWORD

    executor: ruby/default
    steps:
      - checkout

      # Restore cached dependencies
      - restore_cache:
          name: Restore bundle cache
          keys: 
            - goal-tracker-{{ checksum "Gemfile.lock" }}
            - goal-tracker-

      # Install bundle dependencies
      - run: bundle config set --local path 'vendor/bundle'
      - run: bundle install

      # Cache dependencies
      - save_cache:
          name: Store bundle cache
          key: goal-tracker-{{ checksum "Gemfile.lock" }}
          paths: 
            - vendor/bundle
        
      - run: bundle exec rake db:setup

      - persist_to_workspace:
          root: vendor
          paths: bundle


  test:
    docker:
      - image: cimg/ruby:3.0.0-node
        environment:
          RAILS_ENV: test
          PGHOST: 127.0.0.1
          PGUSER: root

      - image: circleci/postgres:latest
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: goal-tracker-test
          POSTGRES_PASSWORD: $POSTGRES_PASSWORD

    executor: ruby/default
    steps:
      - checkout

      # Use built dependencies from build job
      - attach_workspace:
          at: vendor
      - run: bundle config set --local path 'vendor/bundle'

      # Set up database
      - run: bundle exec rake db:setup

      # Run tests & extract results
      - run: mkdir ~/rspec
      - run:
          command: bundle exec rspec --format progress --format RspecJunitFormatter -o ~/rspec/rspec.xml
          when: always
      - store_test_results:
          path: ~/rspec


workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build